/**
 * SUPER ADMIN SYSTEM SETTINGS
 * ============================
 * Global system configuration:
 *  - Email / SMTP with auto-billing
 *  - SMS gateway
 *  - Backup scheduler + restore (with upload & verify)
 *  - Capacity & Health
 *  - Security overview
 */
import React, { useState, useEffect } from 'react';
import api, { base } from '../../utils/api';
import toast from 'react-hot-toast';
import { fDate } from '../../utils/helpers';

function Toggle({ value, onChange, label, desc }) {
  return (
    <div className="flex items-center justify-between py-3">
      <div>
        <p className="text-white text-sm font-medium">{label}</p>
        {desc && <p className="text-xs mt-0.5" style={{ color:'var(--color-text-muted)' }}>{desc}</p>}
      </div>
      <div onClick={()=>onChange(!value)} className="relative w-11 h-6 rounded-full cursor-pointer transition-colors flex-shrink-0"
        style={{ background: value?'var(--color-primary)':'var(--color-surface2)' }}>
        <div className="absolute top-1 w-4 h-4 bg-white rounded-full transition-transform"
          style={{ transform: value?'translateX(22px)':'translateX(4px)' }} />
      </div>
    </div>
  );
}

function UploadBackupPanel({ onUploaded, onRestore }) {
  const [file, setFile] = useState(null);
  const [uploading, setUploading] = useState(false);
  const [validated, setValidated] = useState(null);

  const handleFileChange = (e) => {
    setFile(e.target.files[0]);
    setValidated(null);
  };

  const handleUpload = async () => {
    if (!file) return;
    setUploading(true);
    try {
      const form = new FormData();
      form.append('backupFile', file);
      const { data } = await api.post('/backup/upload', form, {
        headers: { 'Content-Type': 'multipart/form-data' }
      });
      if (data.success) {
        toast.success('✅ Backup verified and uploaded successfully!');
        setValidated(data.backup);
        onUploaded(data.backup);
      } else {
        toast.error(data.message || 'Upload failed');
      }
    } catch (e) {
      toast.error(e.response?.data?.message || 'Upload or validation failed');
    } finally {
      setUploading(false);
    }
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3">
        <label className="flex-1 flex items-center gap-3 px-4 py-3 rounded-xl cursor-pointer transition-all"
          style={{ background: 'var(--color-surface2)', border: '1.5px dashed var(--color-border)' }}>
          <span className="text-2xl">📁</span>
          <div className="flex-1 min-w-0">
            <p className="text-sm font-medium text-white truncate">{file ? file.name : 'Choose backup .zip file…'}</p>
            <p className="text-xs" style={{ color: 'var(--color-text-muted)' }}>
              {file ? (file.size/1024/1024).toFixed(2)+' MB' : 'Only .zip files generated by this system are accepted'}
            </p>
          </div>
          <input type="file" accept=".zip" className="hidden" onChange={handleFileChange} />
        </label>
        <button onClick={handleUpload} disabled={!file || uploading} className="btn-primary flex-shrink-0">
          {uploading ? <><span className="animate-spin inline-block mr-1">⟳</span>Validating…</> : '↑ Upload & Verify'}
        </button>
      </div>

      {validated && (
        <div className="p-4 rounded-xl space-y-3" style={{ background: 'rgba(16,185,129,0.06)', border: '1px solid rgba(16,185,129,0.25)' }}>
          <div className="flex items-center gap-2">
            <span className="text-green-400 text-lg">✅</span>
            <p className="text-sm font-bold text-green-400">Backup Verified — Authentic System Backup</p>
          </div>
          <div className="grid grid-cols-2 gap-2 text-xs">
            <div><span style={{ color: 'var(--color-text-muted)' }}>File:</span> <span className="text-white font-mono truncate">{validated.filename}</span></div>
            <div><span style={{ color: 'var(--color-text-muted)' }}>Size:</span> <span className="text-white">{validated.size}</span></div>
            <div><span style={{ color: 'var(--color-text-muted)' }}>Backup Date:</span> <span className="text-white">{validated.manifest?.timestamp ? new Date(validated.manifest.timestamp).toLocaleString() : '—'}</span></div>
            <div><span style={{ color: 'var(--color-text-muted)' }}>Collections:</span> <span className="text-white">{validated.manifest?.collections}</span></div>
            <div><span style={{ color: 'var(--color-text-muted)' }}>Total Records:</span> <span className="text-white">{validated.manifest?.totalDocs?.toLocaleString()}</span></div>
            <div><span style={{ color: 'var(--color-text-muted)' }}>Media Files:</span> <span className="text-white">{validated.manifest?.totalFiles}</span></div>
          </div>
          <button
            onClick={() => onRestore(validated.filename)}
            className="w-full py-2 rounded-xl text-sm font-bold transition-all"
            style={{ background: 'rgba(245,158,11,0.15)', color: '#f59e0b', border: '1px solid rgba(245,158,11,0.3)' }}
          >
            ↩ Restore From This Backup
          </button>
        </div>
      )}
    </div>
  );
}

export default function SuperSystem() {
  const [settings, setSettings] = useState(null);
  const [stats, setStats] = useState(null);
  const [utilization, setUtilization] = useState(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [testEmail, setTestEmail] = useState('');
  const [testSMS, setTestSMS] = useState('');
  const [testing, setTesting] = useState({ email:false, sms:false });
  const [backups, setBackups] = useState([]);
  const [backing, setBacking] = useState(false);
  const [restoring, setRestoring] = useState('');
  const [activeTab, setActiveTab] = useState('email');
  const [progress, setProgress] = useState(null);

  const loadAll = () => {
    Promise.all([
      api.get('/system/settings'),
      api.get('/backup/list').catch(()=>({ data:{ backups:[] } })),
      api.get('/superadmin/stats').catch(()=>({ data:{ stats: null } })),
      api.get('/system/health-stats').catch(()=>({ data:{ utilization: null } }))
    ]).then(([s, b, st, ut]) => {
      setSettings(s.data.settings);
      setBackups(b.data.backups || []);
      setStats(st.data.stats || null);
      setUtilization(ut.data.utilization || null);
    }).catch(()=>{}).finally(()=>setLoading(false));
  };

  useEffect(()=>{ loadAll(); },[]);

  // Auto-refresh backup list when on backup tab
  useEffect(() => {
    if (activeTab !== 'backup') return;
    const interval = setInterval(() => {
      api.get('/backup/list').then(r => setBackups(r.data.backups || [])).catch(()=>{});
    }, 30000); // refresh every 30s
    return () => clearInterval(interval);
  }, [activeTab]);

  useEffect(() => {
    if (activeTab !== 'health') return;
    const interval = setInterval(() => {
      api.get('/system/health-stats')
        .then(r => setUtilization(r.data.utilization))
        .catch(() => {});
    }, 10000);
    return () => clearInterval(interval);
  }, [activeTab]);

  const save = async () => {
    setSaving(true);
    try {
      const { data } = await api.put('/system/settings', settings);
      toast.success(data.message || 'Settings saved successfully!');
    } catch (e) {
      toast.error(e.response?.data?.message || 'Failed to save settings');
    } finally {
      setSaving(false);
    }
  };

  const upd = (path, val) => {
    setSettings(prev => {
      const parts = path.split('.'); const copy = JSON.parse(JSON.stringify(prev));
      let obj = copy;
      for (let i = 0; i < parts.length - 1; i++) { if (!obj[parts[i]]) obj[parts[i]] = {}; obj = obj[parts[i]]; }
      obj[parts[parts.length - 1]] = val; return copy;
    });
  };

  const sendTestEmail = async () => {
    setTesting(t=>({...t,email:true}));
    try { const { data } = await api.post('/system/email/test',{testEmail}); toast[data.success?'success':'error'](data.message); }
    catch(e){ toast.error(e.response?.data?.message||'Test failed'); } finally{setTesting(t=>({...t,email:false}));}
  };

  const sendTestSMS = async () => {
    setTesting(t=>({...t,sms:true}));
    try { const { data } = await api.post('/system/sms/test',{testPhone:testSMS}); toast[data.success?'success':'error'](data.message); }
    catch(e){ toast.error(e.response?.data?.message||'Test failed'); } finally{setTesting(t=>({...t,sms:false}));}
  };

  const startProgressPolling = () => {
    setProgress({ active: true, type: 'init', progress: 0, step: 'Connecting to system database...' });
    const interval = setInterval(() => {
      api.get('/backup/progress-status')
        .then(r => {
          const status = r.data.status;
          setProgress(status);
          if (!status.active) {
            clearInterval(interval);
            api.get('/backup/list').then(b => setBackups(b.data.backups || [])).catch(() => {});
            if (status.success) {
              toast.success(`${status.type === 'backup' ? 'Backup' : 'Restore'} finished successfully!`);
            } else if (status.error) {
              toast.error(`${status.type === 'backup' ? 'Backup' : 'Restore'} failed: ${status.error}`);
            }
            setTimeout(() => setProgress(null), 6000);
          }
        })
        .catch(() => { clearInterval(interval); setProgress(null); });
    }, 600);
  };

  const triggerBackup = async () => {
    setBacking(true);
    try {
      await api.post('/backup/now');
      toast.success('Backup sequence initialized in the background');
      startProgressPolling();
    } catch(e) {
      toast.error(e.response?.data?.message||'Backup initialization failed');
    } finally {
      setBacking(false);
    }
  };

  const restoreBackup = async (filename) => {
    if (!window.confirm(`⚠️ RESTORE from "${filename}"?\n\nThis will REPLACE ALL current data. This cannot be undone.\n\nAre you sure?`)) return;
    setRestoring(filename);
    try {
      await api.post('/backup/restore/' + filename);
      toast.success('Restore sequence initialized in the background');
      startProgressPolling();
    } catch(e) {
      toast.error(e.response?.data?.message||'Restore initialization failed');
    } finally {
      setRestoring('');
    }
  };

  const deleteBackup = async (filename) => {
    if (!window.confirm('Delete backup "' + filename + '"?')) return;
    try { await api.delete('/backup/' + filename); setBackups(b=>b.filter(x=>x.filename!==filename)); toast.success('Deleted'); }
    catch{ toast.error('Failed to delete'); }
  };

  if (loading) return <div className="text-center py-12" style={{ color:'var(--color-text-muted)' }}>Loading…</div>;
  if (!settings) return null;

  const tabs = [
    { id:'email',    label:'✉ Email/SMTP' },
    { id:'sms',      label:'📱 SMS' },
    { id:'backup',   label:'💾 Backup' },
    { id:'health',   label:'⚡ Capacity & Health' },
    { id:'security', label:'🔒 Security' },
  ];

  return (
    <div>
      <div className="flex items-center justify-between mb-6 flex-wrap gap-3">
        <div>
          <h1 className="page-title">System Settings</h1>
          <p className="text-sm" style={{ color:'var(--color-text-muted)' }}>Global configuration — affects all hospitals</p>
        </div>
        <button onClick={save} disabled={saving} className="btn-primary">{saving?'Saving…':'💾 Save All'}</button>
      </div>

      {/* Tab bar */}
      <div className="flex gap-2 mb-6 border-b pb-0" style={{ borderColor:'var(--color-border)' }}>
        {tabs.map(t=>(
          <button key={t.id} onClick={()=>setActiveTab(t.id)}
            className="px-4 py-2.5 text-sm font-medium transition-all"
            style={{ color: activeTab===t.id?'var(--color-primary)':'var(--color-text-muted)',
                     borderBottom: activeTab===t.id?'2px solid var(--color-primary)':'2px solid transparent',
                     marginBottom:'-1px' }}>
            {t.label}
          </button>
        ))}
      </div>

      {/* EMAIL TAB */}
      {activeTab==='email'&&(
        <div className="card max-w-2xl space-y-4">
          <div>
            <h3 className="section-title">Email / SMTP</h3>
            <p className="text-xs mt-1" style={{ color:'var(--color-text-muted)' }}>
              Used for monthly billing, system alerts, and hospital notifications.
            </p>
          </div>
          <div className="divide-y" style={{ borderColor:'var(--color-border)' }}>
            <Toggle value={settings.email?.enabled} onChange={v=>upd('email.enabled',v)} label="Enable Email" desc="Required for auto-billing and notifications" />
          </div>
          {settings.email?.enabled&&(
            <>
              <div>
                <label className="label">Email Provider</label>
                <select className="input" value={settings.email?.provider||'smtp'} onChange={e=>upd('email.provider',e.target.value)}>
                  <option value="smtp">SMTP (any provider)</option>
                  <option value="gmail">Gmail (use App Password)</option>
                  <option value="sendgrid">SendGrid</option>
                </select>
              </div>
              <div className="grid md:grid-cols-2 gap-3">
                {[['email.host','SMTP Host','text','smtp.gmail.com'],
                  ['email.port','Port','number','587'],
                  ['email.user','Username / Email','text'],
                  ['email.password','Password / API Key','password'],
                  ['email.fromName','From Name','text','Hospital eChanneling'],
                  ['email.fromEmail','From Email','email']
                ].map(([k,l,t,ph])=>(
                  <div key={k}>
                    <label className="label">{l}</label>
                    <input type={t} className="input" placeholder={ph||''} value={settings.email?.[k.split('.')[1]]||''}
                      onChange={e=>upd(k,e.target.value)} />
                  </div>
                ))}
              </div>
              <div className="divide-y" style={{ borderColor:'var(--color-border)' }}>
                <Toggle value={settings.email?.secure} onChange={v=>upd('email.secure',v)} label="Use SSL/TLS (port 465)" />
                <Toggle value={settings.email?.autoBilling?.enabled} onChange={v=>upd('email.autoBilling.enabled',v)}
                  label="Auto Monthly Billing" desc="Send invoice emails to each hospital on 1st of month" />
              </div>
              <div className="p-3 rounded-xl flex items-end gap-3" style={{ background:'var(--color-surface2)' }}>
                <div className="flex-1">
                  <label className="label">Test Email Address</label>
                  <input className="input" placeholder="test@example.com" value={testEmail} onChange={e=>setTestEmail(e.target.value)} />
                </div>
                <button onClick={sendTestEmail} disabled={testing.email||!testEmail} className="btn-primary flex-shrink-0">
                  {testing.email?'Sending…':'Send Test'}
                </button>
              </div>
            </>
          )}
          <button onClick={save} disabled={saving} className="btn-primary w-full">{saving?'Saving…':'Save Email Settings'}</button>
        </div>
      )}

      {/* SMS TAB */}
      {activeTab==='sms'&&(
        <div className="card max-w-2xl space-y-4">
          <div>
            <h3 className="section-title">SMS Gateway</h3>
            <p className="text-xs mt-1" style={{ color:'var(--color-text-muted)' }}>
              Global SMS provider. Each hospital can override with their own WhatsApp settings.
            </p>
          </div>
          <div className="divide-y" style={{ borderColor:'var(--color-border)' }}>
            <Toggle value={settings.sms?.enabled} onChange={v=>upd('sms.enabled',v)} label="Enable SMS" desc="Sends booking/queue alerts via SMS" />
          </div>
          {settings.sms?.enabled&&(
            <>
              <div>
                <label className="label">SMS Provider</label>
                <select className="input" value={settings.sms?.provider||'twilio'} onChange={e=>upd('sms.provider',e.target.value)}>
                  <option value="textlk">text.lk (Sri Lanka)</option>
                  <option value="twilio">Twilio</option>
                  <option value="nexmo">Vonage (Nexmo)</option>
                  <option value="aws-sns">AWS SNS</option>
                  <option value="custom">Custom HTTP API</option>
                </select>
              </div>
              <div className="grid md:grid-cols-2 gap-3">
                <div><label className="label">API Key / Account SID</label>
                  <input className="input" value={settings.sms?.apiKey||''} onChange={e=>upd('sms.apiKey',e.target.value)} /></div>
                <div><label className="label">API Secret / Auth Token</label>
                  <input type="password" className="input" value={settings.sms?.apiSecret||''} onChange={e=>upd('sms.apiSecret',e.target.value)} /></div>
                <div><label className="label">Sender ID / Phone Number</label>
                  <input className="input" placeholder="+14155238886" value={settings.sms?.senderId||''} onChange={e=>upd('sms.senderId',e.target.value)} /></div>
                {settings.sms?.provider==='custom'&&(
                  <div><label className="label">API URL</label>
                    <input className="input" value={settings.sms?.apiUrl||''} onChange={e=>upd('sms.apiUrl',e.target.value)} /></div>
                )}
              </div>
              <div className="p-3 rounded-xl flex items-end gap-3" style={{ background:'var(--color-surface2)' }}>
                <div className="flex-1">
                  <label className="label">Test Phone Number</label>
                  <input className="input" placeholder="+94771234567" value={testSMS} onChange={e=>setTestSMS(e.target.value)} />
                </div>
                <button onClick={sendTestSMS} disabled={testing.sms||!testSMS} className="btn-primary flex-shrink-0">
                  {testing.sms?'Sending…':'Send Test'}
                </button>
              </div>
            </>
          )}
          <button onClick={save} disabled={saving} className="btn-primary w-full">{saving?'Saving…':'Save SMS Settings'}</button>
        </div>
      )}

      {/* BACKUP TAB */}
      {activeTab==='backup'&&(
        <div className="max-w-3xl space-y-4">
          {/* Progress card */}
          {progress && (
            <div className="card border animate-fadeIn" style={{ borderColor: progress.error ? 'rgba(239,68,68,0.3)' : progress.success ? 'rgba(16,185,129,0.3)' : 'rgba(var(--color-primary-rgb),0.3)' }}>
              <div className="flex items-center justify-between mb-2">
                <h4 className="text-sm font-bold text-white flex items-center gap-2">
                  <span>{progress.type === 'backup' ? '💾' : progress.type === 'restore' ? '↩' : '⏳'}</span>
                  {progress.type === 'backup' ? 'Database Backup In Progress' : progress.type === 'restore' ? 'Database Restore In Progress' : 'Task Initializing'}
                </h4>
                <span className="text-xs font-mono font-bold px-2 py-0.5 rounded-full"
                  style={{ background: progress.error ? 'rgba(239,68,68,0.2)' : progress.success ? 'rgba(16,185,129,0.2)' : 'rgba(var(--color-primary-rgb),0.2)',
                           color: progress.error ? '#f87171' : progress.success ? '#10b981' : 'var(--color-primary)' }}>
                  {progress.progress}%
                </span>
              </div>
              <div className="w-full bg-slate-800 rounded-full h-3.5 overflow-hidden mb-2">
                <div className="h-full rounded-full transition-all duration-300"
                  style={{ width: `${progress.progress}%`,
                           background: progress.error ? '#ef4444' : progress.success ? '#10b981' : 'var(--color-primary)' }} />
              </div>
              <div className="flex items-center gap-2 text-xs font-medium" style={{ color: progress.error ? '#f87171' : 'var(--color-text-muted)' }}>
                {!(progress.error || progress.success) && <span className="animate-spin inline-block">⏳</span>}
                <span>{progress.step}</span>
              </div>
            </div>
          )}

          {/* Backup config */}
          <div className="card">
            <h3 className="section-title mb-4">Backup Configuration</h3>
            <div className="divide-y mb-4" style={{ borderColor:'var(--color-border)' }}>
              <Toggle value={settings.backup?.enabled} onChange={v=>upd('backup.enabled',v)} label="Auto Daily Backup" desc="Run automatic backups every night" />
            </div>
            {settings.backup?.enabled&&(
              <div className="grid md:grid-cols-3 gap-4 mb-4">
                <div><label className="label">Backup Time</label>
                  <input type="time" className="input" value={settings.backup?.scheduleTime||'01:00'} onChange={e=>upd('backup.scheduleTime',e.target.value)} />
                  <p className="text-xs mt-1" style={{ color:'var(--color-text-muted)' }}>Server local time</p>
                </div>
                <div><label className="label">Keep for (days)</label>
                  <input type="number" className="input" value={settings.backup?.retainDays||30} onChange={e=>upd('backup.retainDays',Number(e.target.value))} /></div>
                <div><label className="label">Storage</label>
                  <select className="input" value={settings.backup?.storageType||'local'} onChange={e=>upd('backup.storageType',e.target.value)}>
                    <option value="local">Local disk</option>
                    <option value="network">Network path</option>
                    <option value="both">Both</option>
                  </select>
                </div>
                {(settings.backup?.storageType==='network'||settings.backup?.storageType==='both')&&(
                  <div className="md:col-span-3"><label className="label">Network Path</label>
                    <input className="input" placeholder="//192.168.1.100/backups or /mnt/nas/backups" value={settings.backup?.networkPath||''} onChange={e=>upd('backup.networkPath',e.target.value)} /></div>
                )}
              </div>
            )}
            <div className="flex gap-3">
              <button onClick={save} disabled={saving} className="btn-primary">{saving?'Saving…':'Save Config'}</button>
              <button onClick={triggerBackup} disabled={backing} className="btn-ghost">
                {backing?<><span className="animate-spin inline-block mr-1">⟳</span>Creating backup…</>:'▶ Backup Now'}
              </button>
            </div>
          </div>

          {/* Upload & Restore */}
          <div className="card">
            <h3 className="section-title mb-1">↑ Upload & Restore a Backup File</h3>
            <p className="text-xs mb-4" style={{ color:'var(--color-text-muted)' }}>
              Upload a previously downloaded <strong>.zip</strong> backup. The system verifies it was generated by this platform before allowing restore.
            </p>
            <UploadBackupPanel
              onUploaded={(b) => setBackups(prev => [b, ...prev.filter(x => x.filename !== b.filename)])}
              onRestore={restoreBackup}
            />
          </div>

          {/* Backup list */}
          <div className="card">
            <div className="flex items-center justify-between mb-4">
              <h3 className="section-title">Backup Files</h3>
              <button onClick={()=>api.get('/backup/list').then(r=>setBackups(r.data.backups||[])).catch(()=>{})} className="btn-ghost text-xs">↻ Refresh</button>
            </div>
            {backups.length===0?(
              <div className="text-center py-8" style={{ color:'var(--color-text-muted)' }}>
                <div className="text-3xl mb-2">💾</div>
                <p>No backups yet. Click "Backup Now" to create one.</p>
                <p className="text-xs mt-2 opacity-60">Note: Backups on cloud servers (Render free tier) are lost on redeploy. Always download important backups locally.</p>
              </div>
            ):(
              <div className="space-y-2">
                {backups.map((b,i)=>(
                  <div key={i} className="flex items-center gap-4 p-3 rounded-xl" style={{ background:'var(--color-surface2)' }}>
                    <div className="text-xl flex-shrink-0">{b.isUploaded ? '📤' : '📦'}</div>
                    <div className="flex-1 min-w-0">
                      <p className="text-white text-sm font-medium font-mono truncate">{b.filename}</p>
                      <p className="text-xs" style={{ color:'var(--color-text-muted)' }}>
                        {b.size} · {b.createdAt ? new Date(b.createdAt).toLocaleString() : ''}
                        {b.isUploaded && <span className="ml-2 px-1.5 py-0.5 rounded text-[9px] font-bold" style={{ background:'rgba(245,158,11,0.15)', color:'#f59e0b' }}>UPLOADED</span>}
                      </p>
                    </div>
                    <div className="flex gap-2 flex-shrink-0">
                      <a href={`${base ? (base.endsWith('/api') ? base : base + '/api') : '/api'}/backup/download/${b.filename}?token=${localStorage.getItem('token')}`} download
                        className="text-xs px-3 py-1.5 rounded-xl transition-all"
                        style={{ background:'rgba(var(--color-primary-rgb),0.1)',color:'var(--color-primary)' }}>
                        ⬇ Download
                      </a>
                      <button onClick={()=>restoreBackup(b.filename)} disabled={!!restoring}
                        className="text-xs px-3 py-1.5 rounded-xl transition-all"
                        style={{ background:'rgba(245,158,11,0.1)',color:'#f59e0b' }}>
                        {restoring===b.filename?'Restoring…':'↩ Restore'}
                      </button>
                      <button onClick={()=>deleteBackup(b.filename)}
                        className="text-xs px-2 py-1.5 rounded-xl"
                        style={{ background:'rgba(239,68,68,0.1)',color:'#ef4444' }}>
                        ✕
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}
            <div className="mt-4 p-3 rounded-xl" style={{ background:'rgba(239,68,68,0.06)', border:'1px solid rgba(239,68,68,0.15)' }}>
              <p className="text-xs font-semibold mb-1" style={{ color:'#f87171' }}>⚠️ Important — Restore Warning</p>
              <p className="text-xs" style={{ color:'var(--color-text-muted)' }}>
                Restoring a backup will replace ALL current data including patients, appointments, and settings. This action cannot be undone. Always download a fresh backup before restoring.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* CAPACITY & HEALTH TAB */}
      {activeTab === 'health' && (
        <div className="max-w-3xl space-y-4">
          {/* Keep-Alive Configuration */}
          <div className="card">
            <h3 className="section-title mb-2">⚡ 24-Hour Keep-Alive Continuous Ping</h3>
            <p className="text-xs mb-4" style={{ color: 'var(--color-text-muted)' }}>
              Prevents the Render container from automatically going to sleep after 15 minutes of inactivity.
            </p>
            <div className="divide-y mb-4" style={{ borderColor: 'var(--color-border)' }}>
              <Toggle
                value={settings.keepAlive?.enabled}
                onChange={v => upd('keepAlive.enabled', v)}
                label="Enable 24-Hour Keep-Alive Service"
                desc="Starts the background ping engine to query your host every 5 minutes"
              />
            </div>
            {settings.keepAlive?.enabled && (
              <div className="space-y-4 mb-4">
                <div>
                  <label className="label">Public Host URL</label>
                  <input type="url" className="input" placeholder="https://hospital-system-t9fq.onrender.com"
                    value={settings.keepAlive?.url || ''} onChange={e => upd('keepAlive.url', e.target.value)} />
                  <p className="text-xs mt-1" style={{ color: 'var(--color-text-muted)' }}>
                    Enter your live backend endpoint.
                  </p>
                </div>
                <div className="p-4 rounded-xl space-y-3" style={{ background: 'var(--color-surface2)', border: '1px solid var(--color-border)' }}>
                  <h4 className="text-sm font-semibold text-white">📡 Connection Status</h4>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
                    <div className="flex justify-between py-1.5 border-b" style={{ borderColor: 'var(--color-border)' }}>
                      <span style={{ color: 'var(--color-text-muted)' }}>Last Ping Time:</span>
                      <span className="font-mono text-white">
                        {settings.keepAlive?.lastPing ? new Date(settings.keepAlive.lastPing).toLocaleString() : 'Never triggered yet'}
                      </span>
                    </div>
                    <div className="flex justify-between py-1.5 border-b" style={{ borderColor: 'var(--color-border)' }}>
                      <span style={{ color: 'var(--color-text-muted)' }}>Ping Status:</span>
                      <span className="font-bold flex items-center gap-1"
                        style={{ color: settings.keepAlive?.lastPingStatus === 'success' ? '#10b981' : '#f59e0b' }}>
                        <span className="w-2 h-2 rounded-full" style={{ background: settings.keepAlive?.lastPingStatus === 'success' ? '#10b981' : '#f59e0b' }} />
                        {settings.keepAlive?.lastPingStatus || 'Pending'}
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            )}
            <button onClick={save} disabled={saving} className="btn-primary w-full md:w-auto">
              {saving ? 'Saving…' : '💾 Save Keep-Alive Settings'}
            </button>
          </div>

          {/* Live Utilization */}
          <div className="card animate-fadeIn">
            <h3 className="section-title mb-2">⚡ Live Server Utilization & Resource Metrics</h3>
            <p className="text-xs mb-4" style={{ color: 'var(--color-text-muted)' }}>
              Real-time hardware resource consumption. Updated automatically every 10 seconds.
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="p-4 rounded-xl space-y-2 border" style={{ borderColor: 'var(--color-border)', background: 'var(--color-surface2)' }}>
                <div className="flex justify-between items-center text-xs">
                  <span className="font-semibold text-white">💾 RAM Memory Usage</span>
                  <span className="font-mono text-indigo-400 font-bold">{utilization?.memory ? `${utilization.memory.percent}%` : 'Calculating…'}</span>
                </div>
                <div className="w-full rounded-full h-2" style={{ background: 'rgba(255,255,255,0.06)' }}>
                  <div className="h-2 rounded-full transition-all duration-500"
                    style={{ width: utilization?.memory ? `${utilization.memory.percent}%` : '0%', background: 'var(--color-primary)' }} />
                </div>
                <p className="text-xs" style={{ color: 'var(--color-text-muted)' }}>
                  {utilization?.memory ? `Using ${utilization.memory.used} MB of ${utilization.memory.total} MB` : 'Querying…'}
                </p>
              </div>
              <div className="p-4 rounded-xl space-y-2 border" style={{ borderColor: 'var(--color-border)', background: 'var(--color-surface2)' }}>
                <div className="flex justify-between items-center text-xs">
                  <span className="font-semibold text-white">⚙️ CPU Load Average</span>
                  <span className="font-mono text-teal-400 font-bold">{utilization?.cpu ? `${utilization.cpu.load}` : 'Measuring…'}</span>
                </div>
                <div className="w-full rounded-full h-2" style={{ background: 'rgba(255,255,255,0.06)' }}>
                  <div className="h-2 rounded-full transition-all duration-500"
                    style={{ width: utilization?.cpu ? `${Math.min((utilization.cpu.load / Math.max(utilization.cpu.cores, 1)) * 100, 100)}%` : '0%', background: '#0d9488' }} />
                </div>
                <p className="text-xs" style={{ color: 'var(--color-text-muted)' }}>
                  {utilization?.cpu ? `Load across ${utilization.cpu.cores} CPU Cores` : 'Calculating…'}
                </p>
              </div>
              <div className="p-4 rounded-xl flex items-center gap-3 border" style={{ borderColor: 'var(--color-border)', background: 'var(--color-surface2)' }}>
                <div className="text-3xl">🔌</div>
                <div className="flex-1 min-w-0">
                  <p className="text-white text-xs font-semibold">Active WebSockets</p>
                  <p className="text-lg font-bold font-mono text-emerald-400">
                    {utilization?.activeSockets !== undefined ? `${utilization.activeSockets} Live Clients` : 'Calculating…'}
                  </p>
                  <p className="text-xs" style={{ color: 'var(--color-text-muted)' }}>Real-time connected doctors, staff and displays</p>
                </div>
              </div>
              <div className="p-4 rounded-xl flex items-center gap-3 border" style={{ borderColor: 'var(--color-border)', background: 'var(--color-surface2)' }}>
                <div className="text-3xl">⏱️</div>
                <div className="flex-1 min-w-0">
                  <p className="text-white text-xs font-semibold">Server Uptime</p>
                  <p className="text-lg font-bold font-mono text-amber-400">{utilization?.uptime ? utilization.uptime : 'Calculating…'}</p>
                  <p className="text-xs" style={{ color: 'var(--color-text-muted)' }}>Continuous time since last deployment restart</p>
                </div>
              </div>
            </div>
          </div>

          {/* Core Engine Status */}
          <div className="card">
            <h3 className="section-title mb-4">🖥️ Core Engine Status</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {[
                { label: 'API Server', desc: 'Main Express web application gateway', status: 'Online', ok: true },
                { label: 'Database Connection', desc: 'MongoDB primary connection status', status: utilization?.dbStatus || 'Connected', ok: utilization?.dbStatus === 'Connected' || !utilization },
                { label: 'Socket.IO Engine', desc: 'WebSocket push notification link', status: 'Active (Instant)', ok: true },
                { label: 'Automated Reminders', desc: 'Follow-ups and session summaries scheduler', status: 'Running', ok: true },
              ].map(item => (
                <div key={item.label} className="p-3.5 rounded-xl border flex flex-col justify-between" style={{ borderColor: 'var(--color-border)', background: 'var(--color-surface2)' }}>
                  <div>
                    <h4 className="text-white text-sm font-semibold">{item.label}</h4>
                    <p className="text-xs mt-0.5" style={{ color: 'var(--color-text-muted)' }}>{item.desc}</p>
                  </div>
                  <div className="flex items-center gap-2 mt-3 text-xs font-semibold" style={{ color: item.ok ? '#10b981' : '#f59e0b' }}>
                    <span className="w-2.5 h-2.5 rounded-full animate-pulse" style={{ background: item.ok ? '#10b981' : '#f59e0b' }} />
                    {item.status}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Capacity */}
          <div className="card">
            <h3 className="section-title mb-2">📊 System Capacity & DB Metrics</h3>
            <p className="text-xs mb-4" style={{ color: 'var(--color-text-muted)' }}>Real-time document occupancy counts stored in the cluster.</p>
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="border-b" style={{ borderColor: 'var(--color-border)' }}>
                    <th className="py-2 text-xs font-bold uppercase tracking-wider" style={{ color: 'var(--color-text-muted)' }}>Entity / Collection</th>
                    <th className="py-2 text-xs font-bold uppercase tracking-wider text-right" style={{ color: 'var(--color-text-muted)' }}>Active Records</th>
                    <th className="py-2 text-xs font-bold uppercase tracking-wider text-right" style={{ color: 'var(--color-text-muted)' }}>Capacity Limit</th>
                  </tr>
                </thead>
                <tbody className="divide-y" style={{ borderColor: 'var(--color-border)' }}>
                  <tr className="text-sm"><td className="py-3 text-white font-medium">🏥 Registered Hospitals</td><td className="py-3 text-right font-mono font-bold text-teal-400">{stats?.hospitals || 0}</td><td className="py-3 text-right text-xs" style={{ color: 'var(--color-text-muted)' }}>Unlimited</td></tr>
                  <tr className="text-sm"><td className="py-3 text-white font-medium">🩺 Medical Practitioners</td><td className="py-3 text-right font-mono font-bold text-indigo-400">{stats?.doctors || 0}</td><td className="py-3 text-right text-xs" style={{ color: 'var(--color-text-muted)' }}>Per Hospital Subscription</td></tr>
                  <tr className="text-sm"><td className="py-3 text-white font-medium">👥 Registered Patients</td><td className="py-3 text-right font-mono font-bold text-amber-400">{stats?.patients || 0}</td><td className="py-3 text-right text-xs" style={{ color: 'var(--color-text-muted)' }}>Per Hospital Subscription</td></tr>
                  <tr className="text-sm"><td className="py-3 text-white font-medium">📅 Appointments Booked</td><td className="py-3 text-right font-mono font-bold text-emerald-400">{stats?.appointments || 0}</td><td className="py-3 text-right text-xs" style={{ color: 'var(--color-text-muted)' }}>Unlimited</td></tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}

      {/* SECURITY TAB */}
      {activeTab==='security'&&(
        <div className="card max-w-2xl">
          <h3 className="section-title mb-4">Security Status</h3>
          <div className="space-y-1">
            {[
              ['Helmet.js HTTP Headers',         'Protection against XSS, clickjacking, MIME sniffing', true],
              ['Rate Limiting',                  'API: 300/15min · Auth: 15/15min · Bookings: 10/min', true],
              ['NoSQL Injection Prevention',     'express-mongo-sanitize replaces $ and . in input', true],
              ['HTTP Parameter Pollution',       'hpp middleware blocks duplicate params', true],
              ['Response Compression',           'gzip via compression middleware', true],
              ['JWT Token Authentication',       '7-day expiry, HS256 signed', true],
              ['Password Hashing',               'bcryptjs with cost factor 12', true],
              ['CORS Policy',                    'Restricted to FRONTEND_URL env variable', true],
              ['Doctor Data Isolation',          'Doctors can only access their own patient records', true],
              ['Hospital Data Isolation',        'All queries scoped by hospitalId', true],
              ['Audit Logging',                  'Coming in next version', false],
              ['HTTPS/TLS',                      'Configure in your web server (Nginx/Apache)', null],
              ['MongoDB Encryption at Rest',     'Enable in MongoDB Atlas or mongod.conf', null],
            ].map(([l, v, ok])=>(
              <div key={l} className="flex items-center justify-between py-2.5 border-b" style={{ borderColor:'var(--color-border)' }}>
                <span className="text-sm" style={{ color:'var(--color-text-muted)' }}>{l}</span>
                <span className="flex items-center gap-1.5 text-xs font-medium text-right max-w-xs"
                  style={{ color: ok===true?'#10b981':ok===false?'#f87171':'#94a3b8' }}>
                  <div className="w-1.5 h-1.5 rounded-full flex-shrink-0"
                    style={{ background: ok===true?'#10b981':ok===false?'#f87171':'#64748b' }} />
                  {v}
                </span>
              </div>
            ))}
          </div>
          <div className="mt-5 p-4 rounded-xl space-y-2" style={{ background:'rgba(var(--color-primary-rgb),0.06)', border:'1px solid rgba(var(--color-primary-rgb),0.2)' }}>
            <p className="text-sm font-semibold" style={{ color:'var(--color-primary)' }}>Production Checklist</p>
            {[
              'Set a strong JWT_SECRET (32+ random characters) in .env',
              "Enable HTTPS with a valid SSL certificate (Let's Encrypt is free)",
              'Use MongoDB Atlas with encryption at rest enabled',
              'Set up firewall rules: only allow port 443 (HTTPS) publicly',
              'Enable MongoDB Atlas IP whitelist to server IP only',
              'Set NODE_ENV=production in your deployment',
              'Use a process manager like PM2 to keep server running',
              'Set up log rotation and monitoring (e.g. Sentry, Datadog)',
            ].map((t,i)=>(
              <p key={i} className="text-xs flex items-start gap-2" style={{ color:'var(--color-text-muted)' }}>
                <span style={{ color:'var(--color-primary)', flexShrink:0 }}>□</span>{t}
              </p>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
